export const authConstant = {
    USER_LOGIN: 'USER_LOGIN',
    GOOGLEUSER_LOGIN: 'GOOGLEUSER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    USER_DELETE: 'USER_DELETE'
}

export const userConstant = {
    GET_ONLINE_USERS: 'GET_ONLINE_USERS',
    SET_NEWPERSON: 'SET_NEWPERSON',
    GET_MESSAGE: 'GET_MESSAGE',
    GET_NEWMESSAGE: 'GET_NEWMESSAGE',
    GET_CHAT: 'GET_CHAT',
    GET_CHATUSERS: 'GET_CHATUSERS',
    SEARCH: 'SEARCH',
    CLEAR_CHAT_PERSON: 'CLEAR_CHAT_PERSON',
    GET_UNSEENMESSAGES: 'GET_UNSEENMESSAGES'
}

export const groupConstant = {
    CREATE_GROUP: 'CREATE_GROUP',
    GET_GROUPLIST: 'GET_GROUPLIST',
    NEW_MESSAGE: 'NEW_MESSAGE',
    GROUP_MESSAGES: 'GROUP_MESSAGES',
    GROUP_MEMBERS: 'GROUP_MEMBERS'
}